@host=https://localhost:7161
POST {{host}}/rooms
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsInN1YiI6ImZhM2RmYTg1LTMzMTYtNGRiZC1iMGE3LTA4ZGQ3YzU0NDM5NCIsImp0aSI6IjE1MTQxMGNlLTg0MjgtNDRlYS1iZTdlLWQwM2YyNzgzOGQ4MyIsImVtYWlsIjoiQWRtaW5AbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IkFkbWluIEFkbWluVGVzdCIsImV4cCI6MTc0NTI2NzEwNywiaXNzIjoiUmVzdEF1dGgiLCJhdWQiOiJSZWFjdEFwcCJ9.hj2NAb0V8AEEr6osMnNUbOuar2FKVpQSfDEZ2LFcXCk
Content-Type: application/json
{
    "m2": 200
}