@host=https://localhost:7084
POST {{host}}/auth/refresh
Cookie: REFRESH_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTdHVkZW50Iiwic3ViIjoiMmU5MDQ4NmYtNzkxZS00ZDQ4LTNiNjAtMDhkZDc4NTVmZjk3IiwianRpIjoiZDE3MmMyYzAtNDM0Yy00ZThmLTgyMGEtMGE3ZmU5NjdjMDM5IiwiZW1haWwiOiJUZXN0ZXJAbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IlRlc3RlIFRlc3RlcnNlbiIsImV4cCI6MTc0NDQ3ODExMSwiaXNzIjoiUmVzdEF1dGgiLCJhdWQiOiJSZWFjdEFwcCJ9.xnmlp7z0V3GxMv8DkqyEwhj89nRJZ5tZRqHEEqK6qYE
Content-Type: application/json