apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      initContainers:
        - name: wait-for-mssql
          image: busybox
          command: ['sh', '-c', 'until nc -z mssql 1433; do echo waiting for mssql; sleep 5; done;']
      containers:
      - name: auth-api
        image: auth-api-image
        imagePullPolicy: IfNotPresent
        env:
        - name: CorsOptions__AllowedOrigins__0
          value: "http://localhost:3000"
        - name: ConnectionStrings__IdentityConnection
          value: "Server=mssql;Database=AuthReact;User Id=sa;Password=Your_password123;TrustServerCertificate=True;MultipleActiveResultSets=true"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api
spec:
  selector:
    app: auth-api
  ports:
    - port: 8080
