apiVersion: apps/v1
kind: Deployment
metadata:
  name: rooms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rooms
  template:
    metadata:
      labels:
        app: rooms
    spec:
      containers:
      - name: rooms
        image: rooms-image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html/config.json
          subPath: config.json
      volumes:
      - name: config-volume
        configMap:
          name: react-config

---
apiVersion: v1
kind: Service
metadata:
  name: rooms
spec:
  type: NodePort
  selector:
    app: rooms
  ports:
    - port: 80
      nodePort: 30001